# ══════════════════════════════════════════════════════════════════ # BEARING FAULT DIAGNOSIS — ANN / MLP # Input: bearing_features_phase3.csv (300 rows × 9 features + 1 label) # Output: 4-class fault classifier (OK, IR, OR, RE) # ══════════════════════════════════════════════════════════════════importnumpy asnp importpandas aspd importmatplotlib.pyplot asplt fromsklearn.model_selection importtrain_test_split fromsklearn.preprocessing importStandardScaler,
LabelEncoder fromsklearn.metrics importclassification_report,
confusion_matrix importtensorflow astf fromtensorflow.keras.models importSequential fromtensorflow.keras.layers importDense,
Dropout fromtensorflow.keras.utils importto_categorical fromtensorflow.keras.callbacks importEarlyStopping importseaborn assns # ── STEP 1: LOAD DATA ─────────────────────────────────────────────df=pd.read_csv('bearing_features_phase3.csv' ) # Feature columns — same 9 features from your Phase 3feature_cols=['mean' ,
'std' ,
'variance' ,
'rms' ,
'peak' ,
'peak_to_peak' ,
'crest_factor' ,
'kurtosis' ,
'skewness' ] X=df[feature_cols].values # shape: (300, 9)y_raw=df['Fault' ].values # ['OK',
'IR',
'OR',
'RE',
...]print(f"Dataset shape: {X.shape}" ) # (300, 9)print(f"Classes: {np.unique(y_raw)}" ) # ['IR' 'OK' 'OR' 'RE']print(df['Fault' ].value_counts()) #~75 per class# ── STEP 2: LABEL ENCODING ────────────────────────────────────────# Convert string labels to integers: IR→1,
OK→0,
OR→2,
RE→3le=LabelEncoder() y_int=le.fit_transform(y_raw) # [0,
1,
2,
3,
...]print(f"Class mapping: {dict(zip(le.classes_, le.transform(le.classes_)))}" ) # {
    'IR': 0, 'OK':1, 'OR':2, 'RE':3
}

— alphabetical ordern_classes=len(le.classes_) # 4# One-hot encode: [0,
1,
2,
3] → [[1,
0,
0,
0],
[0,
1,
0,
0],
...]# Required for Softmax+Categorical Cross-Entropyy_onehot=to_categorical(y_int, num_classes=n_classes) print(f"One-hot shape: {y_onehot.shape}" ) # (300, 4)# ── STEP 3: TRAIN-TEST SPLIT ──────────────────────────────────────# 80/20 split,
stratified to maintain class distributionX_train,
X_test,
y_train,
y_test=train_test_split(X, y_onehot,
    test_size=0.2,
    random_state=42,
    stratify=y_int # stratify on integer labels, not one-hot) print(f"Train: {X_train.shape}, Test: {X_test.shape}" ) # Train: (240, 9) Test: (60, 9)# ── STEP 4: STANDARDSCALER ────────────────────────────────────────# FIT only on training data — then TRANSFORM both train and test# If you fit on all 300 rows: data leakage (test stats contaminate model)scaler=StandardScaler() X_train_scaled=scaler.fit_transform(X_train) # fit+transform trainX_test_scaled=scaler.transform(X_test) # transform only — no fit !# After scaling: mean≈0,
std≈1 for each of the 9 features# Kurtosis: was 0.25–172,
now roughly -1 to+3 (z-score)# ── STEP 5: BUILD THE ANN ─────────────────────────────────────────tf.random.set_seed(42) # reproducibilitymodel=Sequential([ # Input shape: (9, ) — 9 features per bearing Dense(64, activation='relu' , input_shape=(9, ),
        name='hidden_1' ),
    # → output: (batch, 64). Each of 64 neurons: z=W₁x+b₁, a=ReLU(z) # Why 64? Start with 2-4× input size. Tune via validation loss. Dropout(0.3, name='dropout_1' ),
    # 30% of neurons randomly zeroed in each forward pass (training only) # Forces redundant representations → prevents memorizing 240 samples Dense(32, activation='relu' , name='hidden_2' ),
    # → output: (batch, 32). Compresses 64→32 features further. Dropout(0.2, name='dropout_2' ),

    Dense(4, activation='softmax' , name='output' ),
    # → output: (batch, 4). 4 probabilities summing to 1.0 # Softmax: ŷᵢ=e^zᵢ / Σe^zⱼ → [P(IR), P(OK), P(OR), P(RE)]]) model.summary() # Total trainable params:~2,
852 — tiny ! RF had much more complexity.# ── STEP 6: COMPILE ───────────────────────────────────────────────model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    # Adam: adaptive learning rate per parameter. Best default optimizer. # lr=0.001 is the standard starting point for Adam. loss='categorical_crossentropy' ,
    # Categorical CE for multi-class one-hot targets. # L=−Σ yᵢ·log(ŷᵢ) — only the true class term survives. metrics=['accuracy' ]) # ── STEP 7: CALLBACKS ─────────────────────────────────────────────early_stop=EarlyStopping(monitor='val_loss' , # watch validation loss patience=20, # stop if no improvement for 20 epochs restore_best_weights=True, # revert to best epoch's weights
 verbose=1) # Equivalent to your cross-validation: prevents overfitting on 240 samples# ── STEP 8: TRAIN ─────────────────────────────────────────────────history=model.fit(X_train_scaled, y_train,
    epochs=200, # maximum 200 epochs (early stopping will cut this) batch_size=32, # process 32 samples, then update weights once # 240 samples / 32 batch=7.5 → 8 iterations per epoch validation_split=0.2, # hold out 20% of train for val (48 samples) callbacks=[early_stop],
    verbose=1) # ── STEP 9: EVALUATE ──────────────────────────────────────────────test_loss,
test_acc=model.evaluate(X_test_scaled, y_test, verbose=0) print(f"Test Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)" ) # Predictionsy_pred_prob=model.predict(X_test_scaled) # shape: (60, 4)y_pred_int=np.argmax(y_pred_prob, axis=1) # index of max probabilityy_true_int=np.argmax(y_test, axis=1) # recover integer from one-hotprint(classification_report(y_true_int, y_pred_int,
        target_names=le.classes_)) # Shows precision,
recall,
F1 for each class — like your Phase 4# ── STEP 10: TRAINING CURVES ──────────────────────────────────────fig,
(ax1, ax2)=plt.subplots(1, 2, figsize=(12, 4)) ax1.plot(history.history['accuracy' ], label='Train Acc' , color='#7fff5a' ) ax1.plot(history.history['val_accuracy' ], label='Val Acc' , color='#38e0f0' ) ax1.set_title('Accuracy over Epochs' );
ax1.legend();
ax1.set_ylim(0, 1) ax2.plot(history.history['loss' ], label='Train Loss' , color='#ffb830' ) ax2.plot(history.history['val_loss' ], label='Val Loss' , color='#ff5c7a' ) ax2.set_title('Loss over Epochs' );
ax2.legend() plt.tight_layout();
plt.show() # ── STEP 11: CONFUSION MATRIX ─────────────────────────────────────cm=confusion_matrix(y_true_int, y_pred_int) plt.figure(figsize=(6, 5)) sns.heatmap(cm, annot=True, fmt='d' , cmap='Blues' ,
    xticklabels=le.classes_, yticklabels=le.classes_) plt.title('ANN Confusion Matrix — Bearing Fault' ) plt.ylabel('True Label' );
plt.xlabel('Predicted' ) plt.tight_layout();
plt.show()
---
# ══════════════════════════════════════════════════════════════════ # 1D CNN FOR BEARING FAULT DIAGNOSIS # Input: raw vibration signals,
shape (N_recordings, 15625) # Data augmentation: windowing to create more samples # ══════════════════════════════════════════════════════════════════importnumpy asnp importpandas aspd fromsklearn.model_selection importtrain_test_split fromsklearn.preprocessing importLabelEncoder importtensorflow astf fromtensorflow.keras.models importSequential fromtensorflow.keras.layers import(Conv1D, MaxPooling1D, GlobalAveragePooling1D,
    Dense, Dropout, BatchNormalization) fromtensorflow.keras.utils importto_categorical fromtensorflow.keras.callbacks importEarlyStopping,
ReduceLROnPlateau # ── STEP 1: LOAD RAW SIGNALS ──────────────────────────────────────# Assume df has columns: Data_No (1-300),
Acceleration,
Faultdf_raw=pd.read_csv('bearing_data.csv' ) # the original 4.6M row filefs=15625# sampling frequencysignals,
labels=[],
[] fordata_no indf_raw['Data_No' ].unique(): segment=df_raw[df_raw['Data_No' ]==data_no] sig=segment['Acceleration' ].values # shape: (15625, )fault=segment['Fault' ].iloc[0] signals.append(sig) labels.append(fault) X_raw=np.array(signals) # shape: (300, 15625)y_raw=np.array(labels) # ── STEP 2: WINDOWING — DATA AUGMENTATION ─────────────────────────# Problem: 300 samples → too few for CNN# Solution: slide a 1024-sample window with 50% overlap# 300 recordings ×~29 windows=~8700 samples !window_size=1024hop_size=512# 50% overlapX_wins,
y_wins=[],
[] fori,
(sig, label) inenumerate(zip(X_raw, y_raw)): forstart inrange(0, len(sig) - window_size + 1, hop_size): window=sig[start : start+window_size] # Normalize each window to zero mean,
unit variancewindow=(window - window.mean()) / (window.std() + 1e-8) X_wins.append(window) y_wins.append(label) X_wins=np.array(X_wins) # shape: (~8700, 1024)y_wins=np.array(y_wins) print(f"After windowing: {X_wins.shape}" ) # ── STEP 3: ENCODE & SPLIT ────────────────────────────────────────le=LabelEncoder() y_int=le.fit_transform(y_wins) y_onehot=to_categorical(y_int, num_classes=4) # Reshape for Conv1D: (N, window_size, 1) — the '1' is channels# Like a grayscale image has 1 channel;
vibration has 1 signalX_wins=X_wins.reshape(-1, window_size, 1) # (N, 1024, 1)X_train,
X_test,
y_train,
y_test=train_test_split(X_wins, y_onehot, test_size=0.2, random_state=42, stratify=y_int) print(f"Train: {X_train.shape}, Test: {X_test.shape}" ) # Train: (~6960, 1024, 1) Test: (~1740, 1024, 1)# ── STEP 4: BUILD 1D CNN ──────────────────────────────────────────defbuild_cnn_1d(input_shape=(1024, 1), n_classes=4): model=Sequential([ # ── CONV BLOCK 1 ────────────────────────────────────────── Conv1D(filters=32, kernel_size=64, activation='relu' ,
        padding='same' , input_shape=input_shape, name='conv1' ),
    # Input: (batch, 1024, 1) # Output: (batch, 1024, 32) — padding='same' keeps length # Kernel: (64, 1, 32) — 64-sample window × 1 channel × 32 filters # Each of 32 filters learns a DIFFERENT 64-sample pattern BatchNormalization(), # normalize activations → stable training MaxPooling1D(pool_size=4, name='pool1' ),
    # Output: (batch, 256, 32) — keeps highest activation per 4 samples # MaxPool: if spike was at position 100 or 101, both detected ✓ # ── CONV BLOCK 2 ────────────────────────────────────────── Conv1D(64, kernel_size=32, activation='relu' ,
        padding='same' , name='conv2' ),
    # Output: (batch, 256, 64) — learns combinations of Block 1 patterns BatchNormalization(),
    MaxPooling1D(4, name='pool2' ),
    # Output: (batch, 64, 64) # ── CONV BLOCK 3 ────────────────────────────────────────── Conv1D(128, kernel_size=16, activation='relu' ,
        padding='same' , name='conv3' ),
    # Output: (batch, 64, 128) BatchNormalization(),
    GlobalAveragePooling1D(name='gap' ),
    # Average across ALL 64 time positions → (batch, 128) # Better than Flatten (which is position-sensitive) # ── CLASSIFIER HEAD ─────────────────────────────────────── Dense(64, activation='relu' , name='dense1' ),
    Dropout(0.3),
    Dense(n_classes, activation='softmax' , name='output' ),
    ], name='cnn_1d_bearing' ) returnmodel cnn=build_cnn_1d(input_shape=(window_size, 1)) cnn.summary() # ── STEP 5: COMPILE AND TRAIN ─────────────────────────────────────cnn.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy' ,
    metrics=['accuracy' ]) callbacks=[ EarlyStopping(monitor='val_loss' , patience=15, restore_best_weights=True),
ReduceLROnPlateau(monitor='val_loss' , factor=0.5, patience=8, min_lr=1e-6),
# ReduceLROnPlateau: halve LR if val_loss plateaus for 8 epochs# Helps fine-tune near minimum — like reducing GridSearchCV step size] cnn_history=cnn.fit(X_train, y_train,
    epochs=100,
    batch_size=64, # larger batch OK — more windows available validation_split=0.2,
    callbacks=callbacks,
    verbose=1) # ── STEP 6: EVALUATE ──────────────────────────────────────────────test_loss,
test_acc=cnn.evaluate(X_test, y_test, verbose=0) print(f"CNN Test Accuracy: {test_acc:.4f}" ) # ── STEP 7: VISUALIZE WHAT CNN LEARNED ───────────────────────────# Plot the 32 learned kernels from Conv Layer 1kernels=cnn.get_layer('conv1' ).get_weights()[0] # shape: (64, 1, 32)fig,
axes=plt.subplots(4, 8, figsize=(16, 8)) fori,
ax inenumerate(axes.flat): ax.plot(kernels[:, 0, i], linewidth=0.8) # kernel iax.set_title(f'K{i}' , fontsize=7) ax.axis('off' ) plt.suptitle('Learned Conv1 Kernels — What CNN Detects' , fontsize=12) plt.tight_layout();
plt.show() # Some kernels will look like spike detectors,
some like low-pass filters# Compare these to your manually crafted Phase 3 features !
---
# ══════════════════════════════════════════════════════════════════ # SIMPLE RNN — BEARING FAULT DIAGNOSIS # Treats each window as a sequence of individual samples # ══════════════════════════════════════════════════════════════════importnumpy asnp fromtensorflow.keras.models importSequential fromtensorflow.keras.layers importSimpleRNN,
Dense,
Dropout fromtensorflow.keras.utils importto_categorical # Reuse X_wins,
y_onehot from CNN section (shape: (N, 1024, 1))# For RNN: input shape is (timesteps, features_per_step)# We treat each of 1024 timesteps as having 1 feature (the amplitude)X_rnn=X_wins.reshape(-1, 1024, 1) # (N, 1024, 1) — same as CNNX_tr,
X_te,
y_tr,
y_te=train_test_split(X_rnn, y_onehot, test_size=0.2, random_state=42) # ── RNN MODEL ─────────────────────────────────────────────────────rnn_model=Sequential([ SimpleRNN(units=64, # 64 hidden state dimensions activation='tanh' , # hₜ=tanh(Wₓxₜ + Wₕhₜ₋₁ + b) return_sequences=True, # return hₜ at EVERY timestep (needed for stacking) input_shape=(1024, 1),
        name='rnn_1' ),
    # Output: (batch, 1024, 64) — hidden state for each of 1024 timesteps Dropout(0.3),

    SimpleRNN(units=32,
        activation='tanh' ,
        return_sequences=False, # return ONLY the final hidden state name='rnn_2' ),
    # Output: (batch, 32) — summary of entire sequence # This is the "memory" of the whole 1024-sample window Dropout(0.2),
    Dense(16, activation='relu' ),
    Dense(4, activation='softmax' , name='output' )], name='simple_rnn_bearing' ) rnn_model.summary() # SimpleRNN(64): params=64×1+64×64+64=4,
224 (Wₓ + Wₕ + b)# Note: 64×64=Wₕ (recurrent weights) — same weights applied each step !rnn_model.compile(optimizer='adam' ,
    loss='categorical_crossentropy' ,
    metrics=['accuracy' ]) # ── TRAINING NOTE ─────────────────────────────────────────────────# RNN is SLOW on 1024-step sequences (1024 sequential operations)# Use smaller window for demonstration: 128 stepsX_small=X_wins[:,
::8,
:] # downsample: take every 8th sample → 128 stepsX_s_tr,
X_s_te,
y_s_tr,
y_s_te=train_test_split(X_small, y_onehot, test_size=0.2, random_state=42) rnn_model_small=Sequential([ SimpleRNN(32, return_sequences=True, input_shape=(128, 1)),
    SimpleRNN(16, return_sequences=False),
    Dense(4, activation='softmax' )]) rnn_model_small.compile('adam' , 'categorical_crossentropy' , ['accuracy' ]) rnn_hist=rnn_model_small.fit(X_s_tr, y_s_tr,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[EarlyStopping(patience=10, restore_best_weights=True)],
    verbose=1) # EXPECTED: RNN underperforms CNN and LSTM on this task# Why? 1024 steps>>vanishing gradient horizon (~10-20 steps for SimpleRNN)# IR fault periodicity=93 steps → RNN loses that memory completely# This failure motivates LSTM in the next section !
---
# ══════════════════════════════════════════════════════════════════ # LSTM — BEARING FAULT DIAGNOSIS # Same data pipeline as RNN (windowed vibration segments) # Key change: LSTM replaces SimpleRNN → solves vanishing gradient # ══════════════════════════════════════════════════════════════════ from tensorflow.keras.layers import LSTM, Bidirectional # ── STANDARD LSTM ───────────────────────────────────────────────── lstm_model=Sequential([ LSTM(units=64,
            return_sequences=True, # pass all timesteps to next layer input_shape=(1024, 1), # (timesteps=1024, features=1) name='lstm_1' ),
        # LSTM vs SimpleRNN parameter count: # SimpleRNN(64): 64+64×64+64=4, 224 params # LSTM(64): 4 × (64+64×64+64)=16, 896 params (4 gates !) # More parameters → more expressive → better at long sequences Dropout(0.3),

        LSTM(units=32,
            return_sequences=False, # only final state → (batch, 32) name='lstm_2' ),

        Dense(16, activation='relu' ),
        Dropout(0.2),
        Dense(4, activation='softmax' )], name='lstm_bearing' ) lstm_model.summary() # ── BIDIRECTIONAL LSTM (Advanced) ───────────────────────────────── # Processes sequence FORWARD and BACKWARD simultaneously # For vibration: knowing future context helps classify current state bilstm_model=Sequential([ Bidirectional(LSTM(32, return_sequences=True), input_shape=(1024, 1)),
        # Concatenates forward hidden state + backward hidden state # Output: (batch, 1024, 64) — 32 forward + 32 backward Dropout(0.3),
        Bidirectional(LSTM(16)), # return_sequences=False (default) Dense(4, activation='softmax' )], name='bilstm_bearing' ) # ── TRAIN LSTM ──────────────────────────────────────────────────── lstm_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=5e-4),
        # Lower LR than CNN — LSTM has more parameters, needs finer updates loss='categorical_crossentropy' ,
        metrics=['accuracy' ]) lstm_hist=lstm_model.fit(X_tr, y_tr, # using the (N, 1024, 1) data from CNN section epochs=100,
        batch_size=32,
        validation_split=0.2,
        callbacks=[ EarlyStopping(patience=15, restore_best_weights=True),
        ReduceLROnPlateau(factor=0.5, patience=7)],
        verbose=1) lstm_loss, lstm_acc=lstm_model.evaluate(X_te, y_te, verbose=0) print(f"LSTM Accuracy: {lstm_acc:.4f}" ) # ── GATE VALUE INSPECTION ───────────────────────────────────────── # Build a model that outputs gate values (for visualization) import tensorflow.keras.backend as K # Get LSTM layer weights lstm_layer=lstm_model.get_layer('lstm_1' ) Wk=lstm_layer.get_weights() # Wk[0]: kernel (input weights) shape (1, 64×4) — 4 gates, 64 units each # Wk[1]: recurrent kernel shape (64, 64×4) # Wk[2]: bias shape (64×4, ) or (2×64×4, ) depending on implementation print(f"Input kernel shape:     {Wk[0].shape}" ) print(f"Recurrent kernel shape: {Wk[1].shape}" ) # The 4-gate ordering in Keras LSTM: [input, forget, cell, output]
---
# CNN-LSTM hybrid skeleton hybrid=Sequential([ Conv1D(64, 32, activation='relu' , padding='same' , input_shape=(1024, 1)),
        MaxPooling1D(4), # (1024, 1) → (256, 64) Conv1D(128, 16, activation='relu' , padding='same' ),
        MaxPooling1D(4), # (256, 64) → (64, 128) LSTM(64, return_sequences=False), # treat 64 CNN outputs as a sequence Dense(4, activation='softmax' )])