# ══════════════════════════════════════════════════════════════════ # 1D CNN FOR BEARING FAULT DIAGNOSIS # Input: raw vibration signals,
shape (N_recordings, 15625) # Data augmentation: windowing to create more samples # ══════════════════════════════════════════════════════════════════importnumpy asnp importpandas aspd fromsklearn.model_selection importtrain_test_split fromsklearn.preprocessing importLabelEncoder importtensorflow astf fromtensorflow.keras.models importSequential fromtensorflow.keras.layers import(Conv1D, MaxPooling1D, GlobalAveragePooling1D,
    Dense, Dropout, BatchNormalization) fromtensorflow.keras.utils importto_categorical fromtensorflow.keras.callbacks importEarlyStopping,
ReduceLROnPlateau # ── STEP 1: LOAD RAW SIGNALS ──────────────────────────────────────# Assume df has columns: Data_No (1-300),
Acceleration,
Faultdf_raw=pd.read_csv('data.csv' ) # the original 4.6M row filefs=15625# sampling frequencysignals,
labels=[],
[] fordata_no indf_raw['Data_No' ].unique(): segment=df_raw[df_raw['Data_No' ]==data_no] sig=segment['Acceleration' ].values # shape: (15625, )fault=segment['fault' ].iloc[0] signals.append(sig) labels.append(fault) X_raw=np.array(signals) # shape: (300, 15625)y_raw=np.array(labels) # ── STEP 2: WINDOWING — DATA AUGMENTATION ─────────────────────────# Problem: 300 samples → too few for CNN# Solution: slide a 1024-sample window with 50% overlap# 300 recordings ×~29 windows=~8700 samples !window_size=1024hop_size=512# 50% overlapX_wins,
y_wins=[],
[] fori,
(sig, label) inenumerate(zip(X_raw, y_raw)): forstart inrange(0, len(sig) - window_size + 1, hop_size): window=sig[start : start+window_size] # Normalize each window to zero mean,
unit variancewindow=(window - window.mean()) / (window.std() + 1e-8) X_wins.append(window) y_wins.append(label) X_wins=np.array(X_wins) # shape: (~8700, 1024)y_wins=np.array(y_wins) print(f"After windowing: {X_wins.shape}" ) # ── STEP 3: ENCODE & SPLIT ────────────────────────────────────────le=LabelEncoder() y_int=le.fit_transform(y_wins) y_onehot=to_categorical(y_int, num_classes=4) # Reshape for Conv1D: (N, window_size, 1) — the '1' is channels# Like a grayscale image has 1 channel;
vibration has 1 signalX_wins=X_wins.reshape(-1, window_size, 1) # (N, 1024, 1)X_train,
X_test,
y_train,
y_test=train_test_split(X_wins, y_onehot, test_size=0.2, random_state=42, stratify=y_int) print(f"Train: {X_train.shape}, Test: {X_test.shape}" ) # Train: (~6960, 1024, 1) Test: (~1740, 1024, 1)# ── STEP 4: BUILD 1D CNN ──────────────────────────────────────────defbuild_cnn_1d(input_shape=(1024, 1), n_classes=4): model=Sequential([ # ── CONV BLOCK 1 ────────────────────────────────────────── Conv1D(filters=32, kernel_size=64, activation='relu' ,
        padding='same' , input_shape=input_shape, name='conv1' ),
    # Input: (batch, 1024, 1) # Output: (batch, 1024, 32) — padding='same' keeps length # Kernel: (64, 1, 32) — 64-sample window × 1 channel × 32 filters # Each of 32 filters learns a DIFFERENT 64-sample pattern BatchNormalization(), # normalize activations → stable training MaxPooling1D(pool_size=4, name='pool1' ),
    # Output: (batch, 256, 32) — keeps highest activation per 4 samples # MaxPool: if spike was at position 100 or 101, both detected ✓ # ── CONV BLOCK 2 ────────────────────────────────────────── Conv1D(64, kernel_size=32, activation='relu' ,
        padding='same' , name='conv2' ),
    # Output: (batch, 256, 64) — learns combinations of Block 1 patterns BatchNormalization(),
    MaxPooling1D(4, name='pool2' ),
    # Output: (batch, 64, 64) # ── CONV BLOCK 3 ────────────────────────────────────────── Conv1D(128, kernel_size=16, activation='relu' ,
        padding='same' , name='conv3' ),
    # Output: (batch, 64, 128) BatchNormalization(),
    GlobalAveragePooling1D(name='gap' ),
    # Average across ALL 64 time positions → (batch, 128) # Better than Flatten (which is position-sensitive) # ── CLASSIFIER HEAD ─────────────────────────────────────── Dense(64, activation='relu' , name='dense1' ),
    Dropout(0.3),
    Dense(n_classes, activation='softmax' , name='output' ),
    ], name='cnn_1d_bearing' ) returnmodel cnn=build_cnn_1d(input_shape=(window_size, 1)) cnn.summary() # ── STEP 5: COMPILE AND TRAIN ─────────────────────────────────────cnn.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='categorical_crossentropy' ,
    metrics=['accuracy' ]) callbacks=[ EarlyStopping(monitor='val_loss' , patience=15, restore_best_weights=True),
ReduceLROnPlateau(monitor='val_loss' , factor=0.5, patience=8, min_lr=1e-6),
# ReduceLROnPlateau: halve LR if val_loss plateaus for 8 epochs# Helps fine-tune near minimum — like reducing GridSearchCV step size] cnn_history=cnn.fit(X_train, y_train,
    epochs=100,
    batch_size=64, # larger batch OK — more windows available validation_split=0.2,
    callbacks=callbacks,
    verbose=1) # ── STEP 6: EVALUATE ──────────────────────────────────────────────test_loss,
test_acc=cnn.evaluate(X_test, y_test, verbose=0) print(f"CNN Test Accuracy: {test_acc:.4f}" ) # ── STEP 7: VISUALIZE WHAT CNN LEARNED ───────────────────────────# Plot the 32 learned kernels from Conv Layer 1kernels=cnn.get_layer('conv1' ).get_weights()[0] # shape: (64, 1, 32)fig,
axes=plt.subplots(4, 8, figsize=(16, 8)) fori,
ax inenumerate(axes.flat): ax.plot(kernels[:, 0, i], linewidth=0.8) # kernel iax.set_title(f'K{i}' , fontsize=7) ax.axis('off' ) plt.suptitle('Learned Conv1 Kernels — What CNN Detects' , fontsize=12) plt.tight_layout();
plt.show() # Some kernels will look like spike detectors,
some like low-pass filters# Compare these to your manually crafted Phase 3 features !