# ══════════════════════════════════════════════════════════════════ # SIMPLE RNN — BEARING FAULT DIAGNOSIS # Treats each window as a sequence of individual samples # ══════════════════════════════════════════════════════════════════importnumpy asnp fromtensorflow.keras.models importSequential fromtensorflow.keras.layers importSimpleRNN,
Dense,
Dropout fromtensorflow.keras.utils importto_categorical # Reuse X_wins,
y_onehot from CNN section (shape: (N, 1024, 1))# For RNN: input shape is (timesteps, features_per_step)# We treat each of 1024 timesteps as having 1 feature (the amplitude)X_rnn=X_wins.reshape(-1, 1024, 1) # (N, 1024, 1) — same as CNNX_tr,
X_te,
y_tr,
y_te=train_test_split(X_rnn, y_onehot, test_size=0.2, random_state=42) # ── RNN MODEL ─────────────────────────────────────────────────────rnn_model=Sequential([ SimpleRNN(units=64, # 64 hidden state dimensions activation='tanh' , # hₜ=tanh(Wₓxₜ + Wₕhₜ₋₁ + b) return_sequences=True, # return hₜ at EVERY timestep (needed for stacking) input_shape=(1024, 1),
        name='rnn_1' ),
    # Output: (batch, 1024, 64) — hidden state for each of 1024 timesteps Dropout(0.3),

    SimpleRNN(units=32,
        activation='tanh' ,
        return_sequences=False, # return ONLY the final hidden state name='rnn_2' ),
    # Output: (batch, 32) — summary of entire sequence # This is the "memory" of the whole 1024-sample window Dropout(0.2),
    Dense(16, activation='relu' ),
    Dense(4, activation='softmax' , name='output' )], name='simple_rnn_bearing' ) rnn_model.summary() # SimpleRNN(64): params=64×1+64×64+64=4,
224 (Wₓ + Wₕ + b)# Note: 64×64=Wₕ (recurrent weights) — same weights applied each step !rnn_model.compile(optimizer='adam' ,
    loss='categorical_crossentropy' ,
    metrics=['accuracy' ]) # ── TRAINING NOTE ─────────────────────────────────────────────────# RNN is SLOW on 1024-step sequences (1024 sequential operations)# Use smaller window for demonstration: 128 stepsX_small=X_wins[:,
::8,
:] # downsample: take every 8th sample → 128 stepsX_s_tr,
X_s_te,
y_s_tr,
y_s_te=train_test_split(X_small, y_onehot, test_size=0.2, random_state=42) rnn_model_small=Sequential([ SimpleRNN(32, return_sequences=True, input_shape=(128, 1)),
    SimpleRNN(16, return_sequences=False),
    Dense(4, activation='softmax' )]) rnn_model_small.compile('adam' , 'categorical_crossentropy' , ['accuracy' ]) rnn_hist=rnn_model_small.fit(X_s_tr, y_s_tr,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[EarlyStopping(patience=10, restore_best_weights=True)],
    verbose=1) # EXPECTED: RNN underperforms CNN and LSTM on this task# Why? 1024 steps>>vanishing gradient horizon (~10-20 steps for SimpleRNN)# IR fault periodicity=93 steps → RNN loses that memory completely# This failure motivates LSTM in the next section !